import type { User, Mentor, LibraryItem, Session, Certificate, Notification, AdminStats, Badge } from './types';

// ─────────────────────────────────────────────
// هيكل جامعة الأمير سطام بن عبدالعزيز
// كلية الهندسة والحاسب
// ─────────────────────────────────────────────

export const UNIVERSITY_NAME = 'جامعة الأمير سطام بن عبدالعزيز';
export const COLLEGE_NAME = 'كلية هندسة وعلوم الحاسب بالخرج';

/** التخصصات الأربعة */
export const MAJORS = [
  'هندسة البرمجيات',
  'علوم الحاسب',
  'نظم المعلومات',
  'هندسة الحاسب',
];

/** المستويات الدراسية (8 مستويات = 4 سنوات) */
export const ACADEMIC_LEVELS = [
  { value: 1, label: 'المستوى الأول',   year: 'السنة الأولى',   semester: 'الفصل الأول' },
  { value: 2, label: 'المستوى الثاني',  year: 'السنة الأولى',   semester: 'الفصل الثاني' },
  { value: 3, label: 'المستوى الثالث',  year: 'السنة الثانية',  semester: 'الفصل الأول' },
  { value: 4, label: 'المستوى الرابع',  year: 'السنة الثانية',  semester: 'الفصل الثاني' },
  { value: 5, label: 'المستوى الخامس',  year: 'السنة الثالثة', semester: 'الفصل الأول' },
  { value: 6, label: 'المستوى السادس',  year: 'السنة الثالثة', semester: 'الفصل الثاني' },
  { value: 7, label: 'المستوى السابع',  year: 'السنة الرابعة',  semester: 'الفصل الأول' },
  { value: 8, label: 'المستوى الثامن',  year: 'السنة الرابعة',  semester: 'الفصل الثاني' },
];

export function getLevelLabel(level: number): string {
  return ACADEMIC_LEVELS.find(l => l.value === level)?.label ?? `المستوى ${level}`;
}

// ─────────────────────────────────────────────
// قائمة المواد — مُصنَّفة حسب التخصص
// ─────────────────────────────────────────────

// ─────────────────────────────────────────────
// المواد المستخرجة من الخطط الدراسية الرسمية
// (هندسة البرمجيات ENP • علوم الحاسب CSC
//  نظم المعلومات INS • هندسة الحاسب CE)
// ─────────────────────────────────────────────

/**
 * مواد مشتركة بين جميع التخصصات الأربعة
 * (متطلبات الجامعة + متطلبات الكلية المشتركة)
 */
export const SHARED_ALL: string[] = [
  // ── مهارات اللغة الإنجليزية ──
  'مهارات القراءة',
  'مهارات الكتابة',
  'المهارات اللغوية',
  'مهارات الاستماع والمحادثة',
  'مهارات الاتصال',
  'اللغة الإنجليزية للتخصصات العلمية',
  // ── اللغة العربية والدراسات الإسلامية ──
  'التحرير العربي',
  'السيرة النبوية',
  'المدخل إلى الثقافة الإسلامية',
  'الإسلام وبناء المجتمع',
  'أسس النظام الاقتصادي في الإسلام',
  'أسس النظام السياسي في الإسلام',
  // ── رياضيات وفيزياء ──
  'فيزياء عامة (I)',
  'حساب التفاضل',
  'حساب التكامل',
  'الرياضيات المتقطعة',
  'الجبر الخطي لطلاب الحاسب',
  'الإحصاء والاحتمالات لطلبة الحاسب',
  // ── برمجة وقواعد بيانات أساسية ──
  'برمجة الحاسب 1',
  'أساسيات نظم قواعد البيانات',
];

/**
 * مواد مشتركة بين هندسة البرمجيات وعلوم الحاسب فقط
 */
export const SHARED_ENP_CSC: string[] = [
  'فيزياء عامة (II)',
  'برمجة الحاسب 2',
  'أساسيات هندسة البرمجيات',
  'الخوارزميات وتراكيب البيانات',
  'نظم التشغيل',
  'نظم شبكات الحاسب',
  'الطرائق العددية',
  'مقدمة في الذكاء الاصطناعي',
  'برمجة تطبيقات الويب',
  'تعلم الآلة',
  'معالجة الصورة الرقمية',
];

/** مواد تخصص هندسة البرمجيات (ENP) الخاصة */
export const ENP_UNIQUE: string[] = [
  'المعادلات التفاضلية لطلبة الحاسب',
  'تنظيم وتصميم الحاسب',
  'تحليل متطلبات البرمجيات',
  'تطوير البرمجيات الآمنة',
  'التفاعل بين الإنسان والحاسب',
  'تصميم ومعمارية البرمجيات',
  'ضمان جودة البرمجيات',
  'إدارة مشاريع البرمجيات',
  'تطوير تطبيقات الأجهزة المتنقلة',
  'إنشاء البرمجيات',
  'مشروع تخرج 1',
  'مشروع تخرج 2',
];

/** مواد تخصص علوم الحاسب (CSC) الخاصة */
export const CSC_UNIQUE: string[] = [
  'التصميم المنطقي',
  'معمارية الحاسب ولغة التجميع',
  'تراكيب البيانات',
  'تصميم وتحليل الخوارزميات',
  'أساسيات الأمن السيبراني',
  'أخلاقيات الحوسبة وطرق البحث',
  'النظرية الحسابية',
  'البرمجة المتقدمة',
  'لغات البرمجة والمترجمات',
  'الحوسبة الموزعة والمتوازية',
  'مشروع تخرج 1',
  'مشروع تخرج 2',
];

/** مواد تخصص نظم المعلومات (INS) الخاصة */
export const INS_UNIQUE: string[] = [
  'مقدمة في مفاهيم وتطبيقات الذكاء الاصطناعي',
  'مبادئ المحاسبة المالية',
  'أساسيات نظم المعلومات',
  'البرمجة لطلاب نظم المعلومات',
  'نظم إدارة قواعد البيانات',
  'تحليل وتصميم النظم',
  'البنية التحتية لتقنية المعلومات',
  'الأعمال الرقمية',
  'أخلاقيات واستدامة نظم المعلومات',
  'التحليل الكمي',
  'إدارة مشاريع نظم المعلومات',
  'أمن الحاسب والمعلومات',
  'أساسيات علم البيانات',
  'تطوير تطبيقات الويب والمتنقلة',
  'نظم تخطيط موارد المؤسسات',
  'التنقيب في البيانات',
  'استراتيجية وإدارة نظم المعلومات',
  'مشروع تخرج 1',
  'مشروع تخرج 2',
];

/**
 * مواد تخصص هندسة الحاسب (CE) الخاصة
 * مستخرجة من الخطة الدراسية الرسمية لقسم هندسة الحاسب — كلية هندسة وعلوم الحاسب بالخرج
 */
export const CE_UNIQUE: string[] = [
  // ── مواد تظهر أيضاً في ENP وCSC (من SHARED_ENP_CSC) ──
  'فيزياء عامة (II)',
  'برمجة الحاسب 2',
  'الخوارزميات وتراكيب البيانات',
  'نظم التشغيل',
  'مقدمة في الذكاء الاصطناعي',
  // ── مواد إجبارية خاصة بهندسة الحاسب ──
  'التصميم المنطقي',
  'المعادلات التفاضلية لطلبة الحاسب',
  'تنظيم وتصميم الحاسب',
  'الدوائر الكهربائية',
  'نظرية الأعداد',
  'عمارة الحاسب',
  'أنظمة المعالجات الدقيقة',
  'الدوائر الإلكترونية',
  'تحليل الإشارات والنظم',
  'أسس هندسة البرمجيات',
  'أخلاقيات الحوسبة وطرق البحث',
  'أنظمة التحكم',
  'تصميم الأنظمة الرقمية',
  'تراسل البيانات',
  'إدارة مشاريع البرمجيات',
  'تصميم أنظمة الدوائر المتكاملة',
  'شبكات الحاسب',
  'أمن الحاسبات والشبكات',
  'الرابوتية والأتمتة',
  'مشروع تخرج 1',
  'مشروع تخرج 2',
  // ── مواد اختيارية شائعة ──
  'الطرائق العددية',
  'النظرية الحسابية',
  'معالجة الإشارات الرقمية',
  'أنظمة الوقت الحقيقي',
  'الأتمتة الصناعية',
  'الحوسبة السحابية',
  'إنترنت الأشياء',
  'النمذجة والمحاكاة',
];

// ── القوائم الكاملة لكل تخصص (مشتركة + خاصة) ──

export const ENP_ALL: string[] = [...SHARED_ALL, ...SHARED_ENP_CSC, ...ENP_UNIQUE];
export const CSC_ALL: string[] = [...SHARED_ALL, ...SHARED_ENP_CSC, ...CSC_UNIQUE];
export const INS_ALL: string[] = [...SHARED_ALL, ...INS_UNIQUE];
export const CE_ALL:  string[] = [...SHARED_ALL, ...CE_UNIQUE];

/** القائمة الكاملة للمواد (بلا تكرار) */
export const SUBJECTS_LIST: string[] = [
  ...new Set([...ENP_ALL, ...CSC_ALL, ...INS_ALL, ...CE_ALL]),
];

/**
 * المواد مُجمَّعة حسب التخصص للفلاتر
 * — المشتركة تظهر في التخصص المناسب —
 */
export const SUBJECTS_BY_MAJOR: Record<string, string[]> = {
  'مشتركة (جميع التخصصات)': SHARED_ALL,
  'هندسة البرمجيات':         ENP_ALL,
  'علوم الحاسب':             CSC_ALL,
  'نظم المعلومات':           INS_ALL,
  'هندسة الحاسب':            CE_ALL,
};

// ─────────────────────────────────────────────
// الشارات
// ─────────────────────────────────────────────
export const MOCK_BADGES: Badge[] = [
  { id: 'b1', name: 'مرشد نشيط',       description: 'أتمّ 5 جلسات إرشادية',        icon: '⭐', color: 'amber',  type: 'bronze',   earnedAt: '2024-09-15' },
  { id: 'b2', name: 'نجم الملخصات',    description: 'رفع 10 ملخصات في المكتبة',    icon: '📚', color: 'blue',   type: 'silver',   earnedAt: '2024-10-01' },
  { id: 'b3', name: 'المرشد المتميز',   description: 'حصل على تقييم 4.8+',          icon: '🏆', color: 'gold',   type: 'gold',     earnedAt: '2024-11-10' },
  { id: 'b4', name: 'الريادي',          description: 'أرشد أكثر من 50 طالباً',      icon: '🚀', color: 'purple', type: 'platinum', earnedAt: '2025-01-05' },
  { id: 'b5', name: 'حارس المعرفة',    description: 'محتواه تجاوز 1000 تحميل',     icon: '🛡️', color: 'green',  type: 'gold',     earnedAt: '2024-12-20' },
  { id: 'b6', name: 'أول خطوة',         description: 'أتم أول جلسة إرشادية',        icon: '👣', color: 'teal',   type: 'bronze',   earnedAt: '2024-09-05' },
];

// ─────────────────────────────────────────────
// المستخدمون التجريبيون
// ─────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'سارة محمد العتيبي',
    email: 'sara.ateebi@psau.edu.sa',
    role: 'student',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'علوم الحاسب',
    year: 4,                        // المستوى الرابع
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara&backgroundColor=b6e3f4',
    points: 340,
    badges: [MOCK_BADGES[0], MOCK_BADGES[5]],
    joinedAt: '2024-09-01',
  },
  {
    id: 'u2',
    name: 'محمد عبدالله الزهراني',
    email: 'mhd.zahrani@psau.edu.sa',
    role: 'student',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'هندسة البرمجيات',
    year: 5,                        // المستوى الخامس
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mhd&backgroundColor=c0aede',
    points: 120,
    badges: [],
    joinedAt: '2024-09-01',
  },
];

// ─────────────────────────────────────────────
// المرشدون التجريبيون
// ─────────────────────────────────────────────
export const MOCK_MENTORS: Mentor[] = [
  {
    id: 'm1',
    name: 'عبدالرحمن سعد السلمي',
    email: 'abdulrahman.salmi@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'علوم الحاسب',
    year: 7,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=abdulrahman&backgroundColor=ffd5dc',
    points: 1850,
    badges: [MOCK_BADGES[0], MOCK_BADGES[1], MOCK_BADGES[2], MOCK_BADGES[3]],
    joinedAt: '2024-09-01',
    subjects: [
      'تراكيب البيانات',
      'تصميم وتحليل الخوارزميات',
      'أساسيات نظم قواعد البيانات',
      'أساسيات هندسة البرمجيات',
      'البرمجة المتقدمة',
    ],
    bio: 'طالب علوم حاسب في المستوى السابع. شغوف بتبسيط مفاهيم الخوارزميات والبرمجة. ساعدت أكثر من 80 طالباً في الفصل الماضي.',
    rating: 4.9,
    totalSessions: 94,
    totalStudents: 83,
    available: true,
    sessionTypes: ['online', 'in-person'],
  },
  {
    id: 'm2',
    name: 'نورة خالد القحطاني',
    email: 'noura.qahtani@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'هندسة البرمجيات',
    year: 8,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=noura&backgroundColor=d1fae5',
    points: 1420,
    badges: [MOCK_BADGES[0], MOCK_BADGES[1], MOCK_BADGES[4]],
    joinedAt: '2024-09-01',
    subjects: [
      'حساب التفاضل',
      'حساب التكامل',
      'الجبر الخطي لطلاب الحاسب',
      'الرياضيات المتقطعة',
      'الإحصاء والاحتمالات لطلبة الحاسب',
      'الطرائق العددية',
    ],
    bio: 'طالبة هندسة برمجيات في المستوى الثامن. أساعد الطلاب على تجاوز مواد الرياضيات بطريقة مبسطة ومنطقية.',
    rating: 4.8,
    totalSessions: 67,
    totalStudents: 55,
    available: true,
    sessionTypes: ['online'],
  },
  {
    id: 'm3',
    name: 'فيصل عبدالعزيز المطيري',
    email: 'faisal.mutairi@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'هندسة الحاسب',
    year: 6,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=faisal&backgroundColor=fef3c7',
    points: 980,
    badges: [MOCK_BADGES[0], MOCK_BADGES[5]],
    joinedAt: '2024-10-01',
    subjects: [
      'التصميم المنطقي',
      'تنظيم وتصميم الحاسب',
      'الدوائر الكهربائية',
      'عمارة الحاسب',
      'تحليل الإشارات والنظم',
    ],
    bio: 'طالب هندسة حاسب في المستوى السادس. أجيد تبسيط مفاهيم العتاد والدوائر الرقمية. أؤمن بأن الفهم أهم من الحفظ.',
    rating: 4.6,
    totalSessions: 38,
    totalStudents: 31,
    available: false,
    sessionTypes: ['in-person'],
  },
  {
    id: 'm4',
    name: 'ريم سعيد الدوسري',
    email: 'reem.dosari@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'نظم المعلومات',
    year: 7,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reem&backgroundColor=e0e7ff',
    points: 1210,
    badges: [MOCK_BADGES[0], MOCK_BADGES[2], MOCK_BADGES[5]],
    joinedAt: '2024-09-15',
    subjects: [
      'أساسيات نظم المعلومات',
      'تحليل وتصميم النظم',
      'نظم إدارة قواعد البيانات',
      'أمن الحاسب والمعلومات',
      'إدارة مشاريع نظم المعلومات',
      'البنية التحتية لتقنية المعلومات',
    ],
    bio: 'طالبة نظم معلومات في المستوى السابع. متخصصة في قواعد البيانات وأمن المعلومات، أشارك ملخصاتي وأساعد زملائي في المواد التقنية.',
    rating: 4.7,
    totalSessions: 52,
    totalStudents: 44,
    available: true,
    sessionTypes: ['online', 'in-person'],
  },
  {
    id: 'm5',
    name: 'خالد ناصر الشهري',
    email: 'khalid.shahri@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'نظم المعلومات',
    year: 6,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khalid&backgroundColor=fce7f3',
    points: 760,
    badges: [MOCK_BADGES[0], MOCK_BADGES[5]],
    joinedAt: '2024-10-10',
    subjects: [
      'مبادئ المحاسبة المالية',
      'التحليل الكمي',
      'التنقيب في البيانات',
      'أساسيات علم البيانات',
      'نظم تخطيط موارد المؤسسات',
    ],
    bio: 'طالب نظم معلومات في المستوى السادس. أساعد زملائي في المواد التحليلية والإدارية وأسعى لتطبيق المفاهيم النظرية على أمثلة واقعية.',
    rating: 4.5,
    totalSessions: 29,
    totalStudents: 24,
    available: true,
    sessionTypes: ['online', 'in-person'],
  },
  {
    id: 'm6',
    name: 'أحمد محمد الغامدي',
    email: 'ahmad.ghamdi@psau.edu.sa',
    role: 'mentor',
    university: UNIVERSITY_NAME,
    college: COLLEGE_NAME,
    major: 'هندسة البرمجيات',
    year: 8,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad&backgroundColor=dcfce7',
    points: 1100,
    badges: [MOCK_BADGES[0], MOCK_BADGES[1], MOCK_BADGES[5]],
    joinedAt: '2024-09-01',
    subjects: [
      'تصميم ومعمارية البرمجيات',
      'ضمان جودة البرمجيات',
      'إدارة مشاريع البرمجيات',
      'تحليل متطلبات البرمجيات',
      'إنشاء البرمجيات',
      'نظم التشغيل',
    ],
    bio: 'طالب هندسة برمجيات في المستوى الثامن. أتخصص في هندسة الجودة وإدارة المشاريع البرمجية.',
    rating: 4.7,
    totalSessions: 45,
    totalStudents: 38,
    available: true,
    sessionTypes: ['online', 'in-person'],
  },
];

// ─────────────────────────────────────────────
// المكتبة الرقمية
// ─────────────────────────────────────────────
export const MOCK_LIBRARY: LibraryItem[] = [
  {
    id: 'l1',
    title: 'ملخص شامل — تراكيب البيانات',
    description: 'ملخص كامل يغطي القوائم المترابطة، الأشجار الثنائية، الرسوم البيانية، وجداول التشتيت مع أمثلة بلغة C++',
    subject: 'تراكيب البيانات',
    courseName: 'CSC211',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    uploadedById: 'm1',
    uploadedByName: 'عبدالرحمن سعد السلمي',
    uploadedAt: '2024-09-20',
    downloads: 342,
    views: 890,
    rating: 4.9,
    ratingsCount: 87,
    tags: ['C++', 'خوارزميات', 'هياكل البيانات'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l2',
    title: 'بنك أسئلة — أساسيات نظم قواعد البيانات',
    description: 'أسئلة الاختبارات السابقة من 2020 إلى 2024 مع إجابات نموذجية وشرح تفصيلي لكل سؤال',
    subject: 'أساسيات نظم قواعد البيانات',
    courseName: 'NAL2511',
    semester: 'الفصل الثاني',
    academicYear: '2024-2025',
    type: 'questions',
    fileUrl: '#',
    uploadedById: 'm1',
    uploadedByName: 'عبدالرحمن سعد السلمي',
    uploadedAt: '2024-10-05',
    downloads: 518,
    views: 1240,
    rating: 4.8,
    ratingsCount: 123,
    tags: ['SQL', 'ERD', 'قواعد البيانات'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l3',
    title: 'شرح مبسّط — حساب التفاضل',
    description: 'ملخص مادة حساب التفاضل بأسلوب سهل مع أمثلة محلولة ونصائح للاختبار',
    subject: 'حساب التفاضل',
    courseName: 'RIYD1050',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    uploadedById: 'm2',
    uploadedByName: 'نورة خالد القحطاني',
    uploadedAt: '2024-09-25',
    downloads: 764,
    views: 1850,
    rating: 4.9,
    ratingsCount: 210,
    tags: ['رياضيات', 'تفاضل', 'تكامل'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l4',
    title: 'محاضرات مسجلة — أساسيات هندسة البرمجيات',
    description: 'سلسلة فيديوهات تشرح مفاهيم هندسة البرمجيات: دورة الحياة، النماذج، UML، وأنماط التصميم',
    subject: 'أساسيات هندسة البرمجيات',
    courseName: 'HAB2111',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'video',
    fileUrl: '#',
    uploadedById: 'm1',
    uploadedByName: 'عبدالرحمن سعد السلمي',
    uploadedAt: '2024-10-15',
    downloads: 289,
    views: 1120,
    rating: 4.7,
    ratingsCount: 95,
    tags: ['Java', 'OOP', 'برمجة'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l5',
    title: 'ملخص — التصميم المنطقي',
    description: 'ملخص شامل يغطي البوابات المنطقية، جداول الحقيقة، المخططات الكارنوف، والعدادات والمسجلات',
    subject: 'التصميم المنطقي',
    courseName: 'HAL1111',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    uploadedById: 'm3',
    uploadedByName: 'فيصل عبدالعزيز المطيري',
    uploadedAt: '2024-11-05',
    downloads: 267,
    views: 610,
    rating: 4.6,
    ratingsCount: 64,
    tags: ['هندسة', 'دوائر كهربائية', 'ثيفنن'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l6',
    title: 'بنك أسئلة — الرياضيات المتقطعة',
    description: 'تجميع أسئلة اختبارات 5 سنوات مع حلول تفصيلية تشمل المنطق، نظرية الرسوم البيانية، والتركيبيات',
    subject: 'الرياضيات المتقطعة',
    courseName: 'AAL1112',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'questions',
    fileUrl: '#',
    uploadedById: 'm2',
    uploadedByName: 'نورة خالد القحطاني',
    uploadedAt: '2024-11-10',
    downloads: 398,
    views: 855,
    rating: 4.7,
    ratingsCount: 102,
    tags: ['رياضيات', 'منطق', 'رسوم بيانية'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l7',
    title: 'شرائح مادة — أمن الحاسب والمعلومات',
    description: 'شرائح منظمة تشمل التشفير، بروتوكولات الأمان، الجدران النارية، وإدارة الهوية والوصول',
    subject: 'أمن الحاسب والمعلومات',
    courseName: 'NAL3801',
    semester: 'الفصل الثاني',
    academicYear: '2024-2025',
    type: 'slides',
    fileUrl: '#',
    uploadedById: 'm4',
    uploadedByName: 'ريم سعيد الدوسري',
    uploadedAt: '2024-11-01',
    downloads: 312,
    views: 720,
    rating: 4.8,
    ratingsCount: 78,
    tags: ['أمن', 'شبكات', 'تشفير'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l8',
    title: 'ملاحظات — تحليل وتصميم النظم',
    description: 'ملاحظات شاملة تغطي دورة حياة النظام، مخططات UML، وتقنيات جمع المتطلبات مع أمثلة',
    subject: 'تحليل وتصميم النظم',
    courseName: 'NAL3611',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'notes',
    fileUrl: '#',
    uploadedById: 'm4',
    uploadedByName: 'ريم سعيد الدوسري',
    uploadedAt: '2024-10-20',
    downloads: 445,
    views: 980,
    rating: 4.6,
    ratingsCount: 134,
    tags: ['نظم المعلومات', 'UML', 'تصميم النظم'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l9',
    title: 'ملخص شامل — نظم التشغيل',
    description: 'ملخص يغطي إدارة العمليات، الجدولة، إدارة الذاكرة، نظام الملفات، والتزامن',
    subject: 'نظم التشغيل',
    courseName: 'AAL3701',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    uploadedById: 'm6',
    uploadedByName: 'أحمد محمد الغامدي',
    uploadedAt: '2024-10-08',
    downloads: 380,
    views: 790,
    rating: 4.8,
    ratingsCount: 91,
    tags: ['هندسة برمجيات', 'علوم حاسب', 'نظم تشغيل'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l10',
    title: 'بنك أسئلة — برمجة الحاسب 1',
    description: 'تجميع أسئلة اختبارات سابقة مع حلول، يغطي المتغيرات، الحلقات، والدوال',
    subject: 'برمجة الحاسب 1',
    courseName: 'AAL1301',
    semester: 'الفصل الأول',
    academicYear: '2024-2025',
    type: 'questions',
    fileUrl: '#',
    uploadedById: 'm1',
    uploadedByName: 'عبدالرحمن سعد السلمي',
    uploadedAt: '2024-09-10',
    downloads: 620,
    views: 1430,
    rating: 4.9,
    ratingsCount: 195,
    tags: ['مشترك', 'برمجة', 'مستوى أول'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l11',
    title: 'ملخص — الإحصاء والاحتمالات لطلبة الحاسب',
    description: 'ملخص مفصّل يغطي الاحتمالات، التوزيعات، الاختبارات الإحصائية، والانحدار مع أمثلة',
    subject: 'الإحصاء والاحتمالات لطلبة الحاسب',
    courseName: 'AHS1050',
    semester: 'الفصل الثاني',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    uploadedById: 'm2',
    uploadedByName: 'نورة خالد القحطاني',
    uploadedAt: '2024-10-01',
    downloads: 510,
    views: 1100,
    rating: 4.8,
    ratingsCount: 143,
    tags: ['مشترك', 'إحصاء', 'احتمالات'],
    college: COLLEGE_NAME,
  },
  {
    id: 'l-pending-1',
    title: 'ملخص — الشبكات الحاسوبية الفصل الثاني',
    description: 'ملخص شامل يغطي طبقات OSI، بروتوكولات TCP/IP، وأساسيات التوجيه والتبديل مع أمثلة عملية',
    subject: 'شبكات الحاسب',
    courseName: 'CSC312',
    semester: 'الفصل الثاني',
    academicYear: '2024-2025',
    type: 'summary',
    fileUrl: '#',
    summaryContent: 'طبقات OSI السبع:\n1. الطبقة المادية\n2. طبقة ربط البيانات\n3. طبقة الشبكة\n4. طبقة النقل\n5. طبقة الجلسة\n6. طبقة التقديم\n7. طبقة التطبيقات\n\nبروتوكول TCP/IP:\n- TCP: بروتوكول موثوق يضمن وصول البيانات بترتيب صحيح\n- IP: مسؤول عن التوجيه بين الشبكات\n- UDP: سريع وغير موثوق، يستخدم في البث المباشر',
    uploadedById: 'm2',
    uploadedByName: 'نورة خالد القحطاني',
    uploadedAt: '2025-03-25',
    downloads: 0,
    views: 0,
    rating: 0,
    ratingsCount: 0,
    tags: ['شبكات', 'OSI', 'TCP/IP'],
    college: COLLEGE_NAME,
    approvalStatus: 'pending' as const,
  },
];

// ─────────────────────────────────────────────
// الجلسات التجريبية
// ─────────────────────────────────────────────
export const MOCK_SESSIONS: Session[] = [
  {
    id: 's1',
    mentorId: 'm1',
    mentorName: 'عبدالرحمن سعد السلمي',
    studentId: 'u1',
    studentName: 'سارة محمد العتيبي',
    subject: 'هياكل البيانات',
    topic: 'شرح الأشجار الثنائية وعمليات الإدراج والحذف',
    date: '2025-03-20',
    startTime: '10:00',
    duration: 60,
    type: 'online',
    status: 'confirmed',
    meetingLink: 'https://meet.google.com/abc-xyz',
  },
  {
    id: 's2',
    mentorId: 'm2',
    mentorName: 'نورة خالد القحطاني',
    studentId: 'u1',
    studentName: 'سارة محمد العتيبي',
    subject: 'حساب التفاضل والتكامل 2',
    topic: 'مراجعة التكامل وتطبيقاته',
    date: '2025-03-22',
    startTime: '14:00',
    duration: 90,
    type: 'online',
    status: 'pending',
  },
  {
    id: 's3',
    mentorId: 'm1',
    mentorName: 'عبدالرحمن سعد السلمي',
    studentId: 'u2',
    studentName: 'محمد عبدالله الزهراني',
    subject: 'قواعد البيانات',
    topic: 'تصميم قاعدة بيانات ومخطط ERD',
    date: '2025-03-15',
    startTime: '11:00',
    duration: 60,
    type: 'in-person',
    status: 'completed',
    rating: 5,
    feedback: 'شرح رائع جداً، استوعبت كل المفاهيم بوضوح. شكراً عبدالرحمن!',
    location: 'مكتبة الكلية — غرفة 3',
  },
  {
    id: 's4',
    mentorId: 'm4',
    mentorName: 'ريم سعيد الدوسري',
    studentId: 'u1',
    studentName: 'سارة محمد العتيبي',
    subject: 'أمن الشبكات',
    topic: 'بروتوكولات التشفير وطبقة SSL/TLS',
    date: '2025-03-10',
    startTime: '09:00',
    duration: 45,
    type: 'online',
    status: 'completed',
    rating: 5,
    feedback: 'ممتازة جداً في الشرح، تبسّط المعلومات بطريقة رائعة',
  },
  {
    id: 's5',
    mentorId: 'm3',
    mentorName: 'فيصل عبدالعزيز المطيري',
    studentId: 'u2',
    studentName: 'محمد عبدالله الزهراني',
    subject: 'الدوائر الكهربائية 1',
    topic: 'تطبيق مبرهنة ثيفنن ونورتون',
    date: '2025-03-25',
    startTime: '16:00',
    duration: 60,
    type: 'in-person',
    status: 'confirmed',
    location: 'مختبر الهندسة الكهربائية',
  },
  {
    id: 's6',
    mentorId: 'm6',
    mentorName: 'أحمد محمد الغامدي',
    studentId: 'u1',
    studentName: 'سارة محمد العتيبي',
    subject: 'منطق الدوائر الرقمية',
    topic: 'تبسيط الدوائر بطريقة كارنوف',
    date: '2025-03-28',
    startTime: '11:00',
    duration: 60,
    type: 'online',
    status: 'pending',
  },
];

// ─────────────────────────────────────────────
// الشهادات
// ─────────────────────────────────────────────
export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: 'c1',
    mentorId: 'm1',
    mentorName: 'عبدالرحمن سعد السلمي',
    college: COLLEGE_NAME,
    major: 'علوم الحاسب',
    type: 'outstanding',
    issuedAt: '2025-01-15',
    sessionsCount: 94,
    averageRating: 4.9,
    totalStudents: 83,
    issuedBy: 'وحدة الإرشاد الأكاديمي — كلية الهندسة والحاسب',
    academicYear: '2024-2025',
  },
  {
    id: 'c2',
    mentorId: 'm2',
    mentorName: 'نورة خالد القحطاني',
    college: COLLEGE_NAME,
    major: 'علوم الحاسب',
    type: 'excellence',
    issuedAt: '2025-01-10',
    sessionsCount: 67,
    averageRating: 4.8,
    totalStudents: 55,
    issuedBy: 'وحدة الإرشاد الأكاديمي — كلية الهندسة والحاسب',
    academicYear: '2024-2025',
  },
  {
    id: 'c3',
    mentorId: 'm4',
    mentorName: 'ريم سعيد الدوسري',
    college: COLLEGE_NAME,
    major: 'نظم المعلومات',
    type: 'excellence',
    issuedAt: '2025-01-12',
    sessionsCount: 52,
    averageRating: 4.7,
    totalStudents: 44,
    issuedBy: 'وحدة الإرشاد الأكاديمي — كلية الهندسة والحاسب',
    academicYear: '2024-2025',
  },
  {
    id: 'c4',
    mentorId: 'm3',
    mentorName: 'فيصل عبدالعزيز المطيري',
    college: COLLEGE_NAME,
    major: 'هندسة الحاسب',
    type: 'appreciation',
    issuedAt: '2024-12-20',
    sessionsCount: 38,
    averageRating: 4.6,
    totalStudents: 31,
    issuedBy: 'وحدة الإرشاد الأكاديمي — كلية الهندسة والحاسب',
    academicYear: '2024-2025',
  },
  {
    id: 'c5',
    mentorId: 'm6',
    mentorName: 'أحمد محمد الغامدي',
    college: COLLEGE_NAME,
    major: 'هندسة الحاسب',
    type: 'appreciation',
    issuedAt: '2025-01-20',
    sessionsCount: 45,
    averageRating: 4.7,
    totalStudents: 38,
    issuedBy: 'وحدة الإرشاد الأكاديمي — كلية الهندسة والحاسب',
    academicYear: '2024-2025',
  },
];

// ─────────────────────────────────────────────
// الإشعارات
// ─────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'تأكيد الجلسة',
    message: 'تم تأكيد جلستك مع عبدالرحمن السلمي في هياكل البيانات يوم الخميس الساعة 10:00',
    type: 'session',
    read: false,
    createdAt: '2025-03-17T08:30:00',
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'محتوى جديد في المكتبة',
    message: 'تم رفع ملخص جديد في مادة هياكل البيانات بواسطة عبدالرحمن السلمي',
    type: 'library',
    read: false,
    createdAt: '2025-03-16T14:20:00',
  },
  {
    id: 'n3',
    userId: 'm1',
    title: 'شهادة جديدة! 🎉',
    message: 'تهانينا! حصلت على شهادة "المرشد المتميز" بناءً على أدائك المتميز في كلية الهندسة والحاسب',
    type: 'certificate',
    read: true,
    createdAt: '2025-01-15T10:00:00',
  },
  {
    id: 'n4',
    userId: 'm1',
    title: 'شارة جديدة مكتسبة! 🏆',
    message: 'مبروك! حصلت على شارة "الريادي" بعد إرشاد أكثر من 50 طالباً',
    type: 'badge',
    read: true,
    createdAt: '2025-01-05T16:45:00',
  },
];

// ─────────────────────────────────────────────
// إحصائيات الإدارة
// ─────────────────────────────────────────────
export const MOCK_ADMIN_STATS: AdminStats = {
  totalStudents: 1247,
  totalMentors: 89,
  totalSessions: 3420,
  totalLibraryItems: 312,
  totalCertificates: 156,
  activeSessionsToday: 23,
  popularSubjects: [
    { name: 'هياكل البيانات',           count: 487 },
    { name: 'حساب التفاضل والتكامل 1',  count: 423 },
    { name: 'قواعد البيانات',            count: 389 },
    { name: 'تحليل الخوارزميات',         count: 312 },
    { name: 'الدوائر الكهربائية 1',      count: 278 },
    { name: 'البرمجة كائنية التوجه',     count: 234 },
  ],
  monthlyActivity: [
    { month: 'سبتمبر', sessions: 245, uploads: 42 },
    { month: 'أكتوبر', sessions: 389, uploads: 67 },
    { month: 'نوفمبر', sessions: 412, uploads: 78 },
    { month: 'ديسمبر', sessions: 298, uploads: 45 },
    { month: 'يناير',  sessions: 456, uploads: 89 },
    { month: 'فبراير', sessions: 523, uploads: 95 },
    { month: 'مارس',   sessions: 340, uploads: 58 },
  ],
  topMentors: [
    { id: 'm1', name: 'عبدالرحمن السلمي',  sessions: 94, rating: 4.9 },
    { id: 'm2', name: 'نورة القحطاني',     sessions: 67, rating: 4.8 },
    { id: 'm4', name: 'ريم الدوسري',       sessions: 52, rating: 4.7 },
    { id: 'm6', name: 'أحمد الغامدي',      sessions: 45, rating: 4.7 },
    { id: 'm3', name: 'فيصل المطيري',      sessions: 38, rating: 4.6 },
    { id: 'm5', name: 'خالد الشهري',       sessions: 29, rating: 4.5 },
  ],
  collegeStats: [
    { college: 'علوم الحاسب',      students: 423, mentors: 31 },
    { college: 'هندسة البرمجيات',  students: 387, mentors: 28 },
    { college: 'نظم المعلومات',    students: 255, mentors: 19 },
    { college: 'هندسة الحاسب',     students: 182, mentors: 11 },
  ],
};
